package DaoImpl;

import Builder.GpsLog;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class GpsLogImpTest {

    private GpsLogImp gpsLogImp;

    @BeforeEach 
    public void setUp() {
        gpsLogImp = new GpsLogImp();
    }

    @Test
    public void testSaveGpsLog() {
        GpsLog log = new GpsLog(
                0, // Assuming ID is autogenerated by DB
                1, // vehicle_id (must be in DB)
                "Central Station",
                LocalDateTime.now(),
                LocalDateTime.now().plusMinutes(15),
                1 // logged_by user id (must exist)
        );

        boolean result = gpsLogImp.saveGpsLog(log);
        assertTrue(result, "GpsLog should be saved successfully");
    }

    @Test
    public void testGetAllLogs() {
        List<GpsLog> logs = gpsLogImp.getAllLogs();
        assertNotNull(logs, "Logs list should not be null");
        assertTrue(logs.size() >= 0, "Logs list size should be zero or more");

        // Optional: print logs for manual verification
        logs.forEach(System.out::println);
    }
}
